### ISSUE TITLE
Make sure the duration results for the public and private transport are being appended in the same order

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#3]
Looping through a two dictionary might yield values in a different order because dictionaries are unordered in Python. 

Therefore, it's best to call your dictionary values with a "key". In your case you want to call the travel times by the destination (under the key "id", and the travel time under ["properties"]["travel_time"]) 

## Steps

- Before starting this ticket **create a branch.**
- Remove all private keys from your code. Look how to best do that on your OS in the [BPI guide](https://best-practice-and-impact.github.io/qa-of-code-guidance/configuration.html#configuring-secrets-as-environment-variables).
- Use git to add/commit/push to your branch.

Update your code to do the following:
- pull out the **value** of "properties" when the value of "id" == [whatever destination you want]
- Destinations is already in a list (which is ordered), so iterate through the list, using it as the destination you want.
- return the travel times to be appended to your results list
- do this for both public and private transport to be sure that the order is correct

**Comment by chloemurrell** [comment]
Progress:
- Set up branch for editing code file to call values based on key and not rely on list order.
- Removed private keys by saving them in .bash_profile file and calling them into the file 
-Had trouble regarding the number of credits for each call however have now resolved this and understand how it works: It actually isn't related to the "fast" version like I previously thought it was a coincidence as pasting this in also reduced the max travel time. Must set the max time to 3600 (1 hour) otherwise it will use more credits. Each additional hour is an extra credit. In future could raise this but for testing purposes and to maximise credits I will leave it as 1 hour.
